millitary_oblik/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("oblik/", include("oblik.urls", namespace="oblik")),
    path("accounts/", include("django.contrib.auth.urls")),

] + debug_toolbar_urls()

oblik/urls.py
from django.urls import path

from oblik.views import (index, Units_List_View, Service_Members_List_View,
                         Service_Members_Detail_View, test_session_view,
                         ServiceManCreateView, Units_List_Create_View,
                         Units_Update_View, Units_Delete_View, Ranks_List_View,
                         Rank_Create_View, Rank_Update_View, Rank_Delete_View,
                         Positions_List_View, Position_Create_View,
                         Position_Update_View, Position_Delete_View,
                         Service_Member_Update_View, Service_Member_Delete_View,
                         register_view, Units_Detail_View) #Create_User_View)

urlpatterns = [
    path("", index, name="index"),
    path("ranks/",
         Ranks_List_View.as_view(),
         name="ranks_list"),
    path("ranks/create",
         Rank_Create_View.as_view(),
         name="rank_create"),
    path("ranks/<int:pk>/update/",
         Rank_Update_View.as_view(),
         name="rank_update"),
    path("ranks/<int:pk>/delete/",
         Rank_Delete_View.as_view(),
         name="rank_delete"),
    path("positions/",
         Positions_List_View.as_view(),
         name="positions_list"),
    path("positions/create",
         Position_Create_View.as_view(),
         name="position_create"),
    path("positions/<int:pk>/update/",
         Position_Update_View.as_view(),
         name="position_update"),
    path("positions/<int:pk>/delete/",
         Position_Delete_View.as_view(),
         name="position_delete"),
    path("units_list/",
         Units_List_View.as_view(),
         name="units_list"),
    path("units_list/create/",
         Units_List_Create_View.as_view(),
         name="units_create"),
    path("units_list/<int:pk>/update/",
         Units_Update_View.as_view(),
         name="units_update"),
    path("units_list/<int:pk>/delete/",
         Units_Delete_View.as_view(),
         name="units_delete"),
    path("units_list/<int:pk>/",
         Units_Detail_View.as_view(),
         name="unit_detail"),
    # path("create_user/",
    #      Create_User_View.as_view(),
    #      name="create_user"),
    path("service_members/",
         Service_Members_List_View.as_view(),
         name="service_members_list"),
    path("service_members/create/", ServiceManCreateView.as_view(),
         name="service_man_create"),
    path("service_members/<int:pk>/update/",
         Service_Member_Update_View.as_view(),
         name="service_member_update"),
    path("service_members/<int:pk>/delete/",
         Service_Member_Delete_View.as_view(),
         name="service_member_delete"),
    path("service_members/<int:pk>/",
         Service_Members_Detail_View.as_view(),
         name="service_member_detail"),
    path("test_session/",
         test_session_view,
         name="test_session"),
    path("register/", register_view, name="register")
]

app_name = "oblik"

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}


    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>


    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>


    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'oblik:index' %}">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="bi bi-shield-fill-check"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Military Oblik</div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'oblik:index' %}">
      <i class="bi bi-speedometer2"></i>
      <span>Головна</span>
    </a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Управління
  </div>

  <!-- Nav Item - Бійці -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'oblik:service_members_list' %}">
      <i class="bi bi-people-fill"></i>
      <span>Бійці</span>
    </a>
  </li>

  <!-- Nav Item - Підрозділи -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'oblik:units_list' %}">
      <i class="bi bi-diagram-3-fill"></i>
      <span>Підрозділи</span>
    </a>
  </li>

  <!-- Nav Item - Звання -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'oblik:ranks_list' %}">
      <i class="bi bi-award-fill"></i>
      <span>Звання</span>
    </a>
  </li>

  <!-- Nav Item - Посади -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'oblik:positions_list' %}">
      <i class="bi bi-briefcase-fill"></i>
      <span>Посади</span>
    </a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>
<!-- End of Sidebar -->